// Code generated by ent, DO NOT EDIT.

package federatedidentity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldUserID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldProvider, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldSubject, v))
}

// UnionID applies equality check predicate on the "union_id" field. It's identical to UnionIDEQ.
func UnionID(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldUnionID, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldLastUsedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldUserID, vs...))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContainsFold(FieldProvider, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContainsFold(FieldSubject, v))
}

// UnionIDEQ applies the EQ predicate on the "union_id" field.
func UnionIDEQ(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldUnionID, v))
}

// UnionIDNEQ applies the NEQ predicate on the "union_id" field.
func UnionIDNEQ(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldUnionID, v))
}

// UnionIDIn applies the In predicate on the "union_id" field.
func UnionIDIn(vs ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldUnionID, vs...))
}

// UnionIDNotIn applies the NotIn predicate on the "union_id" field.
func UnionIDNotIn(vs ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldUnionID, vs...))
}

// UnionIDGT applies the GT predicate on the "union_id" field.
func UnionIDGT(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldUnionID, v))
}

// UnionIDGTE applies the GTE predicate on the "union_id" field.
func UnionIDGTE(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldUnionID, v))
}

// UnionIDLT applies the LT predicate on the "union_id" field.
func UnionIDLT(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldUnionID, v))
}

// UnionIDLTE applies the LTE predicate on the "union_id" field.
func UnionIDLTE(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldUnionID, v))
}

// UnionIDContains applies the Contains predicate on the "union_id" field.
func UnionIDContains(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContains(FieldUnionID, v))
}

// UnionIDHasPrefix applies the HasPrefix predicate on the "union_id" field.
func UnionIDHasPrefix(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldHasPrefix(FieldUnionID, v))
}

// UnionIDHasSuffix applies the HasSuffix predicate on the "union_id" field.
func UnionIDHasSuffix(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldHasSuffix(FieldUnionID, v))
}

// UnionIDIsNil applies the IsNil predicate on the "union_id" field.
func UnionIDIsNil() predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIsNull(FieldUnionID))
}

// UnionIDNotNil applies the NotNil predicate on the "union_id" field.
func UnionIDNotNil() predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotNull(FieldUnionID))
}

// UnionIDEqualFold applies the EqualFold predicate on the "union_id" field.
func UnionIDEqualFold(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEqualFold(FieldUnionID, v))
}

// UnionIDContainsFold applies the ContainsFold predicate on the "union_id" field.
func UnionIDContainsFold(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContainsFold(FieldUnionID, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotNull(FieldLastUsedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.FederatedIdentity {
	return predicate.FederatedIdentity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FederatedIdentity) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FederatedIdentity) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FederatedIdentity) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.NotPredicates(p))
}
