// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/federatedidentity"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// FederatedIdentityCreate is the builder for creating a FederatedIdentity entity.
type FederatedIdentityCreate struct {
	config
	mutation *FederatedIdentityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (fic *FederatedIdentityCreate) SetCreatedAt(t time.Time) *FederatedIdentityCreate {
	fic.mutation.SetCreatedAt(t)
	return fic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fic *FederatedIdentityCreate) SetNillableCreatedAt(t *time.Time) *FederatedIdentityCreate {
	if t != nil {
		fic.SetCreatedAt(*t)
	}
	return fic
}

// SetUpdatedAt sets the "updated_at" field.
func (fic *FederatedIdentityCreate) SetUpdatedAt(t time.Time) *FederatedIdentityCreate {
	fic.mutation.SetUpdatedAt(t)
	return fic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fic *FederatedIdentityCreate) SetNillableUpdatedAt(t *time.Time) *FederatedIdentityCreate {
	if t != nil {
		fic.SetUpdatedAt(*t)
	}
	return fic
}

// SetDeletedAt sets the "deleted_at" field.
func (fic *FederatedIdentityCreate) SetDeletedAt(t time.Time) *FederatedIdentityCreate {
	fic.mutation.SetDeletedAt(t)
	return fic
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fic *FederatedIdentityCreate) SetNillableDeletedAt(t *time.Time) *FederatedIdentityCreate {
	if t != nil {
		fic.SetDeletedAt(*t)
	}
	return fic
}

// SetUserID sets the "user_id" field.
func (fic *FederatedIdentityCreate) SetUserID(i int) *FederatedIdentityCreate {
	fic.mutation.SetUserID(i)
	return fic
}

// SetProvider sets the "provider" field.
func (fic *FederatedIdentityCreate) SetProvider(s string) *FederatedIdentityCreate {
	fic.mutation.SetProvider(s)
	return fic
}

// SetSubject sets the "subject" field.
func (fic *FederatedIdentityCreate) SetSubject(s string) *FederatedIdentityCreate {
	fic.mutation.SetSubject(s)
	return fic
}

// SetUnionID sets the "union_id" field.
func (fic *FederatedIdentityCreate) SetUnionID(s string) *FederatedIdentityCreate {
	fic.mutation.SetUnionID(s)
	return fic
}

// SetNillableUnionID sets the "union_id" field if the given value is not nil.
func (fic *FederatedIdentityCreate) SetNillableUnionID(s *string) *FederatedIdentityCreate {
	if s != nil {
		fic.SetUnionID(*s)
	}
	return fic
}

// SetLastUsedAt sets the "last_used_at" field.
func (fic *FederatedIdentityCreate) SetLastUsedAt(t time.Time) *FederatedIdentityCreate {
	fic.mutation.SetLastUsedAt(t)
	return fic
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (fic *FederatedIdentityCreate) SetNillableLastUsedAt(t *time.Time) *FederatedIdentityCreate {
	if t != nil {
		fic.SetLastUsedAt(*t)
	}
	return fic
}

// SetUser sets the "user" edge to the User entity.
func (fic *FederatedIdentityCreate) SetUser(u *User) *FederatedIdentityCreate {
	return fic.SetUserID(u.ID)
}

// Mutation returns the FederatedIdentityMutation object of the builder.
func (fic *FederatedIdentityCreate) Mutation() *FederatedIdentityMutation {
	return fic.mutation
}

// Save creates the FederatedIdentity in the database.
func (fic *FederatedIdentityCreate) Save(ctx context.Context) (*FederatedIdentity, error) {
	if err := fic.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, fic.sqlSave, fic.mutation, fic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fic *FederatedIdentityCreate) SaveX(ctx context.Context) *FederatedIdentity {
	v, err := fic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fic *FederatedIdentityCreate) Exec(ctx context.Context) error {
	_, err := fic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fic *FederatedIdentityCreate) ExecX(ctx context.Context) {
	if err := fic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fic *FederatedIdentityCreate) defaults() error {
	if _, ok := fic.mutation.CreatedAt(); !ok {
		if federatedidentity.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized federatedidentity.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := federatedidentity.DefaultCreatedAt()
		fic.mutation.SetCreatedAt(v)
	}
	if _, ok := fic.mutation.UpdatedAt(); !ok {
		if federatedidentity.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized federatedidentity.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := federatedidentity.DefaultUpdatedAt()
		fic.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (fic *FederatedIdentityCreate) check() error {
	if _, ok := fic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FederatedIdentity.created_at"`)}
	}
	if _, ok := fic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FederatedIdentity.updated_at"`)}
	}
	if _, ok := fic.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "FederatedIdentity.user_id"`)}
	}
	if _, ok := fic.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "FederatedIdentity.provider"`)}
	}
	if _, ok := fic.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "FederatedIdentity.subject"`)}
	}
	if _, ok := fic.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "FederatedIdentity.user"`)}
	}
	return nil
}

func (fic *FederatedIdentityCreate) sqlSave(ctx context.Context) (*FederatedIdentity, error) {
	if err := fic.check(); err != nil {
		return nil, err
	}
	_node, _spec := fic.createSpec()
	if err := sqlgraph.CreateNode(ctx, fic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	fic.mutation.id = &_node.ID
	fic.mutation.done = true
	return _node, nil
}

func (fic *FederatedIdentityCreate) createSpec() (*FederatedIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &FederatedIdentity{config: fic.config}
		_spec = sqlgraph.NewCreateSpec(federatedidentity.Table, sqlgraph.NewFieldSpec(federatedidentity.FieldID, field.TypeInt))
	)

	if id, ok := fic.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = fic.conflict
	if value, ok := fic.mutation.CreatedAt(); ok {
		_spec.SetField(federatedidentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := fic.mutation.UpdatedAt(); ok {
		_spec.SetField(federatedidentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := fic.mutation.DeletedAt(); ok {
		_spec.SetField(federatedidentity.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := fic.mutation.Provider(); ok {
		_spec.SetField(federatedidentity.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := fic.mutation.Subject(); ok {
		_spec.SetField(federatedidentity.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := fic.mutation.UnionID(); ok {
		_spec.SetField(federatedidentity.FieldUnionID, field.TypeString, value)
		_node.UnionID = value
	}
	if value, ok := fic.mutation.LastUsedAt(); ok {
		_spec.SetField(federatedidentity.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if nodes := fic.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   federatedidentity.UserTable,
			Columns: []string{federatedidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FederatedIdentity.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FederatedIdentityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (fic *FederatedIdentityCreate) OnConflict(opts ...sql.ConflictOption) *FederatedIdentityUpsertOne {
	fic.conflict = opts
	return &FederatedIdentityUpsertOne{
		create: fic,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FederatedIdentity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (fic *FederatedIdentityCreate) OnConflictColumns(columns ...string) *FederatedIdentityUpsertOne {
	fic.conflict = append(fic.conflict, sql.ConflictColumns(columns...))
	return &FederatedIdentityUpsertOne{
		create: fic,
	}
}

type (
	// FederatedIdentityUpsertOne is the builder for "upsert"-ing
	//  one FederatedIdentity node.
	FederatedIdentityUpsertOne struct {
		create *FederatedIdentityCreate
	}

	// FederatedIdentityUpsert is the "OnConflict" setter.
	FederatedIdentityUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *FederatedIdentityUpsert) SetUpdatedAt(v time.Time) *FederatedIdentityUpsert {
	u.Set(federatedidentity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FederatedIdentityUpsert) UpdateUpdatedAt() *FederatedIdentityUpsert {
	u.SetExcluded(federatedidentity.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FederatedIdentityUpsert) SetDeletedAt(v time.Time) *FederatedIdentityUpsert {
	u.Set(federatedidentity.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FederatedIdentityUpsert) UpdateDeletedAt() *FederatedIdentityUpsert {
	u.SetExcluded(federatedidentity.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FederatedIdentityUpsert) ClearDeletedAt() *FederatedIdentityUpsert {
	u.SetNull(federatedidentity.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *FederatedIdentityUpsert) SetUserID(v int) *FederatedIdentityUpsert {
	u.Set(federatedidentity.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *FederatedIdentityUpsert) UpdateUserID() *FederatedIdentityUpsert {
	u.SetExcluded(federatedidentity.FieldUserID)
	return u
}

// SetProvider sets the "provider" field.
func (u *FederatedIdentityUpsert) SetProvider(v string) *FederatedIdentityUpsert {
	u.Set(federatedidentity.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *FederatedIdentityUpsert) UpdateProvider() *FederatedIdentityUpsert {
	u.SetExcluded(federatedidentity.FieldProvider)
	return u
}

// SetSubject sets the "subject" field.
func (u *FederatedIdentityUpsert) SetSubject(v string) *FederatedIdentityUpsert {
	u.Set(federatedidentity.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *FederatedIdentityUpsert) UpdateSubject() *FederatedIdentityUpsert {
	u.SetExcluded(federatedidentity.FieldSubject)
	return u
}

// SetUnionID sets the "union_id" field.
func (u *FederatedIdentityUpsert) SetUnionID(v string) *FederatedIdentityUpsert {
	u.Set(federatedidentity.FieldUnionID, v)
	return u
}

// UpdateUnionID sets the "union_id" field to the value that was provided on create.
func (u *FederatedIdentityUpsert) UpdateUnionID() *FederatedIdentityUpsert {
	u.SetExcluded(federatedidentity.FieldUnionID)
	return u
}

// ClearUnionID clears the value of the "union_id" field.
func (u *FederatedIdentityUpsert) ClearUnionID() *FederatedIdentityUpsert {
	u.SetNull(federatedidentity.FieldUnionID)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *FederatedIdentityUpsert) SetLastUsedAt(v time.Time) *FederatedIdentityUpsert {
	u.Set(federatedidentity.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *FederatedIdentityUpsert) UpdateLastUsedAt() *FederatedIdentityUpsert {
	u.SetExcluded(federatedidentity.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *FederatedIdentityUpsert) ClearLastUsedAt() *FederatedIdentityUpsert {
	u.SetNull(federatedidentity.FieldLastUsedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FederatedIdentity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FederatedIdentityUpsertOne) UpdateNewValues() *FederatedIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(federatedidentity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FederatedIdentity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FederatedIdentityUpsertOne) Ignore() *FederatedIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FederatedIdentityUpsertOne) DoNothing() *FederatedIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FederatedIdentityCreate.OnConflict
// documentation for more info.
func (u *FederatedIdentityUpsertOne) Update(set func(*FederatedIdentityUpsert)) *FederatedIdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FederatedIdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FederatedIdentityUpsertOne) SetUpdatedAt(v time.Time) *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FederatedIdentityUpsertOne) UpdateUpdatedAt() *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FederatedIdentityUpsertOne) SetDeletedAt(v time.Time) *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FederatedIdentityUpsertOne) UpdateDeletedAt() *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FederatedIdentityUpsertOne) ClearDeletedAt() *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *FederatedIdentityUpsertOne) SetUserID(v int) *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *FederatedIdentityUpsertOne) UpdateUserID() *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateUserID()
	})
}

// SetProvider sets the "provider" field.
func (u *FederatedIdentityUpsertOne) SetProvider(v string) *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *FederatedIdentityUpsertOne) UpdateProvider() *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateProvider()
	})
}

// SetSubject sets the "subject" field.
func (u *FederatedIdentityUpsertOne) SetSubject(v string) *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *FederatedIdentityUpsertOne) UpdateSubject() *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateSubject()
	})
}

// SetUnionID sets the "union_id" field.
func (u *FederatedIdentityUpsertOne) SetUnionID(v string) *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetUnionID(v)
	})
}

// UpdateUnionID sets the "union_id" field to the value that was provided on create.
func (u *FederatedIdentityUpsertOne) UpdateUnionID() *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateUnionID()
	})
}

// ClearUnionID clears the value of the "union_id" field.
func (u *FederatedIdentityUpsertOne) ClearUnionID() *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.ClearUnionID()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *FederatedIdentityUpsertOne) SetLastUsedAt(v time.Time) *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *FederatedIdentityUpsertOne) UpdateLastUsedAt() *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *FederatedIdentityUpsertOne) ClearLastUsedAt() *FederatedIdentityUpsertOne {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.ClearLastUsedAt()
	})
}

// Exec executes the query.
func (u *FederatedIdentityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FederatedIdentityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FederatedIdentityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FederatedIdentityUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FederatedIdentityUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *FederatedIdentityCreate) SetRawID(t int) *FederatedIdentityCreate {
	m.mutation.SetRawID(t)
	return m
}

// FederatedIdentityCreateBulk is the builder for creating many FederatedIdentity entities in bulk.
type FederatedIdentityCreateBulk struct {
	config
	err      error
	builders []*FederatedIdentityCreate
	conflict []sql.ConflictOption
}

// Save creates the FederatedIdentity entities in the database.
func (ficb *FederatedIdentityCreateBulk) Save(ctx context.Context) ([]*FederatedIdentity, error) {
	if ficb.err != nil {
		return nil, ficb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ficb.builders))
	nodes := make([]*FederatedIdentity, len(ficb.builders))
	mutators := make([]Mutator, len(ficb.builders))
	for i := range ficb.builders {
		func(i int, root context.Context) {
			builder := ficb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FederatedIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ficb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ficb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ficb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ficb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ficb *FederatedIdentityCreateBulk) SaveX(ctx context.Context) []*FederatedIdentity {
	v, err := ficb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ficb *FederatedIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := ficb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ficb *FederatedIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := ficb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FederatedIdentity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FederatedIdentityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ficb *FederatedIdentityCreateBulk) OnConflict(opts ...sql.ConflictOption) *FederatedIdentityUpsertBulk {
	ficb.conflict = opts
	return &FederatedIdentityUpsertBulk{
		create: ficb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FederatedIdentity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ficb *FederatedIdentityCreateBulk) OnConflictColumns(columns ...string) *FederatedIdentityUpsertBulk {
	ficb.conflict = append(ficb.conflict, sql.ConflictColumns(columns...))
	return &FederatedIdentityUpsertBulk{
		create: ficb,
	}
}

// FederatedIdentityUpsertBulk is the builder for "upsert"-ing
// a bulk of FederatedIdentity nodes.
type FederatedIdentityUpsertBulk struct {
	create *FederatedIdentityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FederatedIdentity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FederatedIdentityUpsertBulk) UpdateNewValues() *FederatedIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(federatedidentity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FederatedIdentity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FederatedIdentityUpsertBulk) Ignore() *FederatedIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FederatedIdentityUpsertBulk) DoNothing() *FederatedIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FederatedIdentityCreateBulk.OnConflict
// documentation for more info.
func (u *FederatedIdentityUpsertBulk) Update(set func(*FederatedIdentityUpsert)) *FederatedIdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FederatedIdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FederatedIdentityUpsertBulk) SetUpdatedAt(v time.Time) *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FederatedIdentityUpsertBulk) UpdateUpdatedAt() *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FederatedIdentityUpsertBulk) SetDeletedAt(v time.Time) *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FederatedIdentityUpsertBulk) UpdateDeletedAt() *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FederatedIdentityUpsertBulk) ClearDeletedAt() *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *FederatedIdentityUpsertBulk) SetUserID(v int) *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *FederatedIdentityUpsertBulk) UpdateUserID() *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateUserID()
	})
}

// SetProvider sets the "provider" field.
func (u *FederatedIdentityUpsertBulk) SetProvider(v string) *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *FederatedIdentityUpsertBulk) UpdateProvider() *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateProvider()
	})
}

// SetSubject sets the "subject" field.
func (u *FederatedIdentityUpsertBulk) SetSubject(v string) *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *FederatedIdentityUpsertBulk) UpdateSubject() *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateSubject()
	})
}

// SetUnionID sets the "union_id" field.
func (u *FederatedIdentityUpsertBulk) SetUnionID(v string) *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetUnionID(v)
	})
}

// UpdateUnionID sets the "union_id" field to the value that was provided on create.
func (u *FederatedIdentityUpsertBulk) UpdateUnionID() *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateUnionID()
	})
}

// ClearUnionID clears the value of the "union_id" field.
func (u *FederatedIdentityUpsertBulk) ClearUnionID() *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.ClearUnionID()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *FederatedIdentityUpsertBulk) SetLastUsedAt(v time.Time) *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *FederatedIdentityUpsertBulk) UpdateLastUsedAt() *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *FederatedIdentityUpsertBulk) ClearLastUsedAt() *FederatedIdentityUpsertBulk {
	return u.Update(func(s *FederatedIdentityUpsert) {
		s.ClearLastUsedAt()
	})
}

// Exec executes the query.
func (u *FederatedIdentityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FederatedIdentityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FederatedIdentityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FederatedIdentityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
