// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/federatedidentity"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// FederatedIdentityUpdate is the builder for updating FederatedIdentity entities.
type FederatedIdentityUpdate struct {
	config
	hooks    []Hook
	mutation *FederatedIdentityMutation
}

// Where appends a list predicates to the FederatedIdentityUpdate builder.
func (fiu *FederatedIdentityUpdate) Where(ps ...predicate.FederatedIdentity) *FederatedIdentityUpdate {
	fiu.mutation.Where(ps...)
	return fiu
}

// SetUpdatedAt sets the "updated_at" field.
func (fiu *FederatedIdentityUpdate) SetUpdatedAt(t time.Time) *FederatedIdentityUpdate {
	fiu.mutation.SetUpdatedAt(t)
	return fiu
}

// SetDeletedAt sets the "deleted_at" field.
func (fiu *FederatedIdentityUpdate) SetDeletedAt(t time.Time) *FederatedIdentityUpdate {
	fiu.mutation.SetDeletedAt(t)
	return fiu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fiu *FederatedIdentityUpdate) SetNillableDeletedAt(t *time.Time) *FederatedIdentityUpdate {
	if t != nil {
		fiu.SetDeletedAt(*t)
	}
	return fiu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (fiu *FederatedIdentityUpdate) ClearDeletedAt() *FederatedIdentityUpdate {
	fiu.mutation.ClearDeletedAt()
	return fiu
}

// SetUserID sets the "user_id" field.
func (fiu *FederatedIdentityUpdate) SetUserID(i int) *FederatedIdentityUpdate {
	fiu.mutation.SetUserID(i)
	return fiu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (fiu *FederatedIdentityUpdate) SetNillableUserID(i *int) *FederatedIdentityUpdate {
	if i != nil {
		fiu.SetUserID(*i)
	}
	return fiu
}

// SetProvider sets the "provider" field.
func (fiu *FederatedIdentityUpdate) SetProvider(s string) *FederatedIdentityUpdate {
	fiu.mutation.SetProvider(s)
	return fiu
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (fiu *FederatedIdentityUpdate) SetNillableProvider(s *string) *FederatedIdentityUpdate {
	if s != nil {
		fiu.SetProvider(*s)
	}
	return fiu
}

// SetSubject sets the "subject" field.
func (fiu *FederatedIdentityUpdate) SetSubject(s string) *FederatedIdentityUpdate {
	fiu.mutation.SetSubject(s)
	return fiu
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (fiu *FederatedIdentityUpdate) SetNillableSubject(s *string) *FederatedIdentityUpdate {
	if s != nil {
		fiu.SetSubject(*s)
	}
	return fiu
}

// SetUnionID sets the "union_id" field.
func (fiu *FederatedIdentityUpdate) SetUnionID(s string) *FederatedIdentityUpdate {
	fiu.mutation.SetUnionID(s)
	return fiu
}

// SetNillableUnionID sets the "union_id" field if the given value is not nil.
func (fiu *FederatedIdentityUpdate) SetNillableUnionID(s *string) *FederatedIdentityUpdate {
	if s != nil {
		fiu.SetUnionID(*s)
	}
	return fiu
}

// ClearUnionID clears the value of the "union_id" field.
func (fiu *FederatedIdentityUpdate) ClearUnionID() *FederatedIdentityUpdate {
	fiu.mutation.ClearUnionID()
	return fiu
}

// SetLastUsedAt sets the "last_used_at" field.
func (fiu *FederatedIdentityUpdate) SetLastUsedAt(t time.Time) *FederatedIdentityUpdate {
	fiu.mutation.SetLastUsedAt(t)
	return fiu
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (fiu *FederatedIdentityUpdate) SetNillableLastUsedAt(t *time.Time) *FederatedIdentityUpdate {
	if t != nil {
		fiu.SetLastUsedAt(*t)
	}
	return fiu
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (fiu *FederatedIdentityUpdate) ClearLastUsedAt() *FederatedIdentityUpdate {
	fiu.mutation.ClearLastUsedAt()
	return fiu
}

// SetUser sets the "user" edge to the User entity.
func (fiu *FederatedIdentityUpdate) SetUser(u *User) *FederatedIdentityUpdate {
	return fiu.SetUserID(u.ID)
}

// Mutation returns the FederatedIdentityMutation object of the builder.
func (fiu *FederatedIdentityUpdate) Mutation() *FederatedIdentityMutation {
	return fiu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (fiu *FederatedIdentityUpdate) ClearUser() *FederatedIdentityUpdate {
	fiu.mutation.ClearUser()
	return fiu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fiu *FederatedIdentityUpdate) Save(ctx context.Context) (int, error) {
	if err := fiu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, fiu.sqlSave, fiu.mutation, fiu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fiu *FederatedIdentityUpdate) SaveX(ctx context.Context) int {
	affected, err := fiu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fiu *FederatedIdentityUpdate) Exec(ctx context.Context) error {
	_, err := fiu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fiu *FederatedIdentityUpdate) ExecX(ctx context.Context) {
	if err := fiu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fiu *FederatedIdentityUpdate) defaults() error {
	if _, ok := fiu.mutation.UpdatedAt(); !ok {
		if federatedidentity.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized federatedidentity.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := federatedidentity.UpdateDefaultUpdatedAt()
		fiu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (fiu *FederatedIdentityUpdate) check() error {
	if _, ok := fiu.mutation.UserID(); fiu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "FederatedIdentity.user"`)
	}
	return nil
}

func (fiu *FederatedIdentityUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fiu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(federatedidentity.Table, federatedidentity.Columns, sqlgraph.NewFieldSpec(federatedidentity.FieldID, field.TypeInt))
	if ps := fiu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fiu.mutation.UpdatedAt(); ok {
		_spec.SetField(federatedidentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := fiu.mutation.DeletedAt(); ok {
		_spec.SetField(federatedidentity.FieldDeletedAt, field.TypeTime, value)
	}
	if fiu.mutation.DeletedAtCleared() {
		_spec.ClearField(federatedidentity.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := fiu.mutation.Provider(); ok {
		_spec.SetField(federatedidentity.FieldProvider, field.TypeString, value)
	}
	if value, ok := fiu.mutation.Subject(); ok {
		_spec.SetField(federatedidentity.FieldSubject, field.TypeString, value)
	}
	if value, ok := fiu.mutation.UnionID(); ok {
		_spec.SetField(federatedidentity.FieldUnionID, field.TypeString, value)
	}
	if fiu.mutation.UnionIDCleared() {
		_spec.ClearField(federatedidentity.FieldUnionID, field.TypeString)
	}
	if value, ok := fiu.mutation.LastUsedAt(); ok {
		_spec.SetField(federatedidentity.FieldLastUsedAt, field.TypeTime, value)
	}
	if fiu.mutation.LastUsedAtCleared() {
		_spec.ClearField(federatedidentity.FieldLastUsedAt, field.TypeTime)
	}
	if fiu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   federatedidentity.UserTable,
			Columns: []string{federatedidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fiu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   federatedidentity.UserTable,
			Columns: []string{federatedidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fiu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{federatedidentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fiu.mutation.done = true
	return n, nil
}

// FederatedIdentityUpdateOne is the builder for updating a single FederatedIdentity entity.
type FederatedIdentityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FederatedIdentityMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (fiuo *FederatedIdentityUpdateOne) SetUpdatedAt(t time.Time) *FederatedIdentityUpdateOne {
	fiuo.mutation.SetUpdatedAt(t)
	return fiuo
}

// SetDeletedAt sets the "deleted_at" field.
func (fiuo *FederatedIdentityUpdateOne) SetDeletedAt(t time.Time) *FederatedIdentityUpdateOne {
	fiuo.mutation.SetDeletedAt(t)
	return fiuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fiuo *FederatedIdentityUpdateOne) SetNillableDeletedAt(t *time.Time) *FederatedIdentityUpdateOne {
	if t != nil {
		fiuo.SetDeletedAt(*t)
	}
	return fiuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (fiuo *FederatedIdentityUpdateOne) ClearDeletedAt() *FederatedIdentityUpdateOne {
	fiuo.mutation.ClearDeletedAt()
	return fiuo
}

// SetUserID sets the "user_id" field.
func (fiuo *FederatedIdentityUpdateOne) SetUserID(i int) *FederatedIdentityUpdateOne {
	fiuo.mutation.SetUserID(i)
	return fiuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (fiuo *FederatedIdentityUpdateOne) SetNillableUserID(i *int) *FederatedIdentityUpdateOne {
	if i != nil {
		fiuo.SetUserID(*i)
	}
	return fiuo
}

// SetProvider sets the "provider" field.
func (fiuo *FederatedIdentityUpdateOne) SetProvider(s string) *FederatedIdentityUpdateOne {
	fiuo.mutation.SetProvider(s)
	return fiuo
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (fiuo *FederatedIdentityUpdateOne) SetNillableProvider(s *string) *FederatedIdentityUpdateOne {
	if s != nil {
		fiuo.SetProvider(*s)
	}
	return fiuo
}

// SetSubject sets the "subject" field.
func (fiuo *FederatedIdentityUpdateOne) SetSubject(s string) *FederatedIdentityUpdateOne {
	fiuo.mutation.SetSubject(s)
	return fiuo
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (fiuo *FederatedIdentityUpdateOne) SetNillableSubject(s *string) *FederatedIdentityUpdateOne {
	if s != nil {
		fiuo.SetSubject(*s)
	}
	return fiuo
}

// SetUnionID sets the "union_id" field.
func (fiuo *FederatedIdentityUpdateOne) SetUnionID(s string) *FederatedIdentityUpdateOne {
	fiuo.mutation.SetUnionID(s)
	return fiuo
}

// SetNillableUnionID sets the "union_id" field if the given value is not nil.
func (fiuo *FederatedIdentityUpdateOne) SetNillableUnionID(s *string) *FederatedIdentityUpdateOne {
	if s != nil {
		fiuo.SetUnionID(*s)
	}
	return fiuo
}

// ClearUnionID clears the value of the "union_id" field.
func (fiuo *FederatedIdentityUpdateOne) ClearUnionID() *FederatedIdentityUpdateOne {
	fiuo.mutation.ClearUnionID()
	return fiuo
}

// SetLastUsedAt sets the "last_used_at" field.
func (fiuo *FederatedIdentityUpdateOne) SetLastUsedAt(t time.Time) *FederatedIdentityUpdateOne {
	fiuo.mutation.SetLastUsedAt(t)
	return fiuo
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (fiuo *FederatedIdentityUpdateOne) SetNillableLastUsedAt(t *time.Time) *FederatedIdentityUpdateOne {
	if t != nil {
		fiuo.SetLastUsedAt(*t)
	}
	return fiuo
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (fiuo *FederatedIdentityUpdateOne) ClearLastUsedAt() *FederatedIdentityUpdateOne {
	fiuo.mutation.ClearLastUsedAt()
	return fiuo
}

// SetUser sets the "user" edge to the User entity.
func (fiuo *FederatedIdentityUpdateOne) SetUser(u *User) *FederatedIdentityUpdateOne {
	return fiuo.SetUserID(u.ID)
}

// Mutation returns the FederatedIdentityMutation object of the builder.
func (fiuo *FederatedIdentityUpdateOne) Mutation() *FederatedIdentityMutation {
	return fiuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (fiuo *FederatedIdentityUpdateOne) ClearUser() *FederatedIdentityUpdateOne {
	fiuo.mutation.ClearUser()
	return fiuo
}

// Where appends a list predicates to the FederatedIdentityUpdate builder.
func (fiuo *FederatedIdentityUpdateOne) Where(ps ...predicate.FederatedIdentity) *FederatedIdentityUpdateOne {
	fiuo.mutation.Where(ps...)
	return fiuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fiuo *FederatedIdentityUpdateOne) Select(field string, fields ...string) *FederatedIdentityUpdateOne {
	fiuo.fields = append([]string{field}, fields...)
	return fiuo
}

// Save executes the query and returns the updated FederatedIdentity entity.
func (fiuo *FederatedIdentityUpdateOne) Save(ctx context.Context) (*FederatedIdentity, error) {
	if err := fiuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, fiuo.sqlSave, fiuo.mutation, fiuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fiuo *FederatedIdentityUpdateOne) SaveX(ctx context.Context) *FederatedIdentity {
	node, err := fiuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fiuo *FederatedIdentityUpdateOne) Exec(ctx context.Context) error {
	_, err := fiuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fiuo *FederatedIdentityUpdateOne) ExecX(ctx context.Context) {
	if err := fiuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fiuo *FederatedIdentityUpdateOne) defaults() error {
	if _, ok := fiuo.mutation.UpdatedAt(); !ok {
		if federatedidentity.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized federatedidentity.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := federatedidentity.UpdateDefaultUpdatedAt()
		fiuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (fiuo *FederatedIdentityUpdateOne) check() error {
	if _, ok := fiuo.mutation.UserID(); fiuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "FederatedIdentity.user"`)
	}
	return nil
}

func (fiuo *FederatedIdentityUpdateOne) sqlSave(ctx context.Context) (_node *FederatedIdentity, err error) {
	if err := fiuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(federatedidentity.Table, federatedidentity.Columns, sqlgraph.NewFieldSpec(federatedidentity.FieldID, field.TypeInt))
	id, ok := fiuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FederatedIdentity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fiuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, federatedidentity.FieldID)
		for _, f := range fields {
			if !federatedidentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != federatedidentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fiuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fiuo.mutation.UpdatedAt(); ok {
		_spec.SetField(federatedidentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := fiuo.mutation.DeletedAt(); ok {
		_spec.SetField(federatedidentity.FieldDeletedAt, field.TypeTime, value)
	}
	if fiuo.mutation.DeletedAtCleared() {
		_spec.ClearField(federatedidentity.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := fiuo.mutation.Provider(); ok {
		_spec.SetField(federatedidentity.FieldProvider, field.TypeString, value)
	}
	if value, ok := fiuo.mutation.Subject(); ok {
		_spec.SetField(federatedidentity.FieldSubject, field.TypeString, value)
	}
	if value, ok := fiuo.mutation.UnionID(); ok {
		_spec.SetField(federatedidentity.FieldUnionID, field.TypeString, value)
	}
	if fiuo.mutation.UnionIDCleared() {
		_spec.ClearField(federatedidentity.FieldUnionID, field.TypeString)
	}
	if value, ok := fiuo.mutation.LastUsedAt(); ok {
		_spec.SetField(federatedidentity.FieldLastUsedAt, field.TypeTime, value)
	}
	if fiuo.mutation.LastUsedAtCleared() {
		_spec.ClearField(federatedidentity.FieldLastUsedAt, field.TypeTime)
	}
	if fiuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   federatedidentity.UserTable,
			Columns: []string{federatedidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fiuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   federatedidentity.UserTable,
			Columns: []string{federatedidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FederatedIdentity{config: fiuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fiuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{federatedidentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fiuo.mutation.done = true
	return _node, nil
}
