// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/federatedidentity"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// FederatedIdentityQuery is the builder for querying FederatedIdentity entities.
type FederatedIdentityQuery struct {
	config
	ctx        *QueryContext
	order      []federatedidentity.OrderOption
	inters     []Interceptor
	predicates []predicate.FederatedIdentity
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FederatedIdentityQuery builder.
func (fiq *FederatedIdentityQuery) Where(ps ...predicate.FederatedIdentity) *FederatedIdentityQuery {
	fiq.predicates = append(fiq.predicates, ps...)
	return fiq
}

// Limit the number of records to be returned by this query.
func (fiq *FederatedIdentityQuery) Limit(limit int) *FederatedIdentityQuery {
	fiq.ctx.Limit = &limit
	return fiq
}

// Offset to start from.
func (fiq *FederatedIdentityQuery) Offset(offset int) *FederatedIdentityQuery {
	fiq.ctx.Offset = &offset
	return fiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fiq *FederatedIdentityQuery) Unique(unique bool) *FederatedIdentityQuery {
	fiq.ctx.Unique = &unique
	return fiq
}

// Order specifies how the records should be ordered.
func (fiq *FederatedIdentityQuery) Order(o ...federatedidentity.OrderOption) *FederatedIdentityQuery {
	fiq.order = append(fiq.order, o...)
	return fiq
}

// QueryUser chains the current query on the "user" edge.
func (fiq *FederatedIdentityQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: fiq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(federatedidentity.Table, federatedidentity.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, federatedidentity.UserTable, federatedidentity.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(fiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FederatedIdentity entity from the query.
// Returns a *NotFoundError when no FederatedIdentity was found.
func (fiq *FederatedIdentityQuery) First(ctx context.Context) (*FederatedIdentity, error) {
	nodes, err := fiq.Limit(1).All(setContextOp(ctx, fiq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{federatedidentity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fiq *FederatedIdentityQuery) FirstX(ctx context.Context) *FederatedIdentity {
	node, err := fiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FederatedIdentity ID from the query.
// Returns a *NotFoundError when no FederatedIdentity ID was found.
func (fiq *FederatedIdentityQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fiq.Limit(1).IDs(setContextOp(ctx, fiq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{federatedidentity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fiq *FederatedIdentityQuery) FirstIDX(ctx context.Context) int {
	id, err := fiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FederatedIdentity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FederatedIdentity entity is found.
// Returns a *NotFoundError when no FederatedIdentity entities are found.
func (fiq *FederatedIdentityQuery) Only(ctx context.Context) (*FederatedIdentity, error) {
	nodes, err := fiq.Limit(2).All(setContextOp(ctx, fiq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{federatedidentity.Label}
	default:
		return nil, &NotSingularError{federatedidentity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fiq *FederatedIdentityQuery) OnlyX(ctx context.Context) *FederatedIdentity {
	node, err := fiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FederatedIdentity ID in the query.
// Returns a *NotSingularError when more than one FederatedIdentity ID is found.
// Returns a *NotFoundError when no entities are found.
func (fiq *FederatedIdentityQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fiq.Limit(2).IDs(setContextOp(ctx, fiq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{federatedidentity.Label}
	default:
		err = &NotSingularError{federatedidentity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fiq *FederatedIdentityQuery) OnlyIDX(ctx context.Context) int {
	id, err := fiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FederatedIdentities.
func (fiq *FederatedIdentityQuery) All(ctx context.Context) ([]*FederatedIdentity, error) {
	ctx = setContextOp(ctx, fiq.ctx, "All")
	if err := fiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FederatedIdentity, *FederatedIdentityQuery]()
	return withInterceptors[[]*FederatedIdentity](ctx, fiq, qr, fiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fiq *FederatedIdentityQuery) AllX(ctx context.Context) []*FederatedIdentity {
	nodes, err := fiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FederatedIdentity IDs.
func (fiq *FederatedIdentityQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fiq.ctx.Unique == nil && fiq.path != nil {
		fiq.Unique(true)
	}
	ctx = setContextOp(ctx, fiq.ctx, "IDs")
	if err = fiq.Select(federatedidentity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fiq *FederatedIdentityQuery) IDsX(ctx context.Context) []int {
	ids, err := fiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fiq *FederatedIdentityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fiq.ctx, "Count")
	if err := fiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fiq, querierCount[*FederatedIdentityQuery](), fiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fiq *FederatedIdentityQuery) CountX(ctx context.Context) int {
	count, err := fiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fiq *FederatedIdentityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fiq.ctx, "Exist")
	switch _, err := fiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fiq *FederatedIdentityQuery) ExistX(ctx context.Context) bool {
	exist, err := fiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FederatedIdentityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fiq *FederatedIdentityQuery) Clone() *FederatedIdentityQuery {
	if fiq == nil {
		return nil
	}
	return &FederatedIdentityQuery{
		config:     fiq.config,
		ctx:        fiq.ctx.Clone(),
		order:      append([]federatedidentity.OrderOption{}, fiq.order...),
		inters:     append([]Interceptor{}, fiq.inters...),
		predicates: append([]predicate.FederatedIdentity{}, fiq.predicates...),
		withUser:   fiq.withUser.Clone(),
		// clone intermediate query.
		sql:  fiq.sql.Clone(),
		path: fiq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (fiq *FederatedIdentityQuery) WithUser(opts ...func(*UserQuery)) *FederatedIdentityQuery {
	query := (&UserClient{config: fiq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fiq.withUser = query
	return fiq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FederatedIdentity.Query().
//		GroupBy(federatedidentity.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fiq *FederatedIdentityQuery) GroupBy(field string, fields ...string) *FederatedIdentityGroupBy {
	fiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FederatedIdentityGroupBy{build: fiq}
	grbuild.flds = &fiq.ctx.Fields
	grbuild.label = federatedidentity.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.FederatedIdentity.Query().
//		Select(federatedidentity.FieldCreatedAt).
//		Scan(ctx, &v)
func (fiq *FederatedIdentityQuery) Select(fields ...string) *FederatedIdentitySelect {
	fiq.ctx.Fields = append(fiq.ctx.Fields, fields...)
	sbuild := &FederatedIdentitySelect{FederatedIdentityQuery: fiq}
	sbuild.label = federatedidentity.Label
	sbuild.flds, sbuild.scan = &fiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FederatedIdentitySelect configured with the given aggregations.
func (fiq *FederatedIdentityQuery) Aggregate(fns ...AggregateFunc) *FederatedIdentitySelect {
	return fiq.Select().Aggregate(fns...)
}

func (fiq *FederatedIdentityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fiq); err != nil {
				return err
			}
		}
	}
	for _, f := range fiq.ctx.Fields {
		if !federatedidentity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fiq.path != nil {
		prev, err := fiq.path(ctx)
		if err != nil {
			return err
		}
		fiq.sql = prev
	}
	return nil
}

func (fiq *FederatedIdentityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FederatedIdentity, error) {
	var (
		nodes       = []*FederatedIdentity{}
		_spec       = fiq.querySpec()
		loadedTypes = [1]bool{
			fiq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FederatedIdentity).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FederatedIdentity{config: fiq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fiq.withUser; query != nil {
		if err := fiq.loadUser(ctx, query, nodes, nil,
			func(n *FederatedIdentity, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fiq *FederatedIdentityQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*FederatedIdentity, init func(*FederatedIdentity), assign func(*FederatedIdentity, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FederatedIdentity)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (fiq *FederatedIdentityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fiq.querySpec()
	_spec.Node.Columns = fiq.ctx.Fields
	if len(fiq.ctx.Fields) > 0 {
		_spec.Unique = fiq.ctx.Unique != nil && *fiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fiq.driver, _spec)
}

func (fiq *FederatedIdentityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(federatedidentity.Table, federatedidentity.Columns, sqlgraph.NewFieldSpec(federatedidentity.FieldID, field.TypeInt))
	_spec.From = fiq.sql
	if unique := fiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fiq.path != nil {
		_spec.Unique = true
	}
	if fields := fiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, federatedidentity.FieldID)
		for i := range fields {
			if fields[i] != federatedidentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if fiq.withUser != nil {
			_spec.Node.AddColumnOnce(federatedidentity.FieldUserID)
		}
	}
	if ps := fiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fiq *FederatedIdentityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fiq.driver.Dialect())
	t1 := builder.Table(federatedidentity.Table)
	columns := fiq.ctx.Fields
	if len(columns) == 0 {
		columns = federatedidentity.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fiq.sql != nil {
		selector = fiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fiq.ctx.Unique != nil && *fiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fiq.predicates {
		p(selector)
	}
	for _, p := range fiq.order {
		p(selector)
	}
	if offset := fiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FederatedIdentityGroupBy is the group-by builder for FederatedIdentity entities.
type FederatedIdentityGroupBy struct {
	selector
	build *FederatedIdentityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (figb *FederatedIdentityGroupBy) Aggregate(fns ...AggregateFunc) *FederatedIdentityGroupBy {
	figb.fns = append(figb.fns, fns...)
	return figb
}

// Scan applies the selector query and scans the result into the given value.
func (figb *FederatedIdentityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, figb.build.ctx, "GroupBy")
	if err := figb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FederatedIdentityQuery, *FederatedIdentityGroupBy](ctx, figb.build, figb, figb.build.inters, v)
}

func (figb *FederatedIdentityGroupBy) sqlScan(ctx context.Context, root *FederatedIdentityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(figb.fns))
	for _, fn := range figb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*figb.flds)+len(figb.fns))
		for _, f := range *figb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*figb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := figb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FederatedIdentitySelect is the builder for selecting fields of FederatedIdentity entities.
type FederatedIdentitySelect struct {
	*FederatedIdentityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fis *FederatedIdentitySelect) Aggregate(fns ...AggregateFunc) *FederatedIdentitySelect {
	fis.fns = append(fis.fns, fns...)
	return fis
}

// Scan applies the selector query and scans the result into the given value.
func (fis *FederatedIdentitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fis.ctx, "Select")
	if err := fis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FederatedIdentityQuery, *FederatedIdentitySelect](ctx, fis.FederatedIdentityQuery, fis, fis.inters, v)
}

func (fis *FederatedIdentitySelect) sqlScan(ctx context.Context, root *FederatedIdentityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fis.fns))
	for _, fn := range fis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
