// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/federatedidentity"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// FederatedIdentityDelete is the builder for deleting a FederatedIdentity entity.
type FederatedIdentityDelete struct {
	config
	hooks    []Hook
	mutation *FederatedIdentityMutation
}

// Where appends a list predicates to the FederatedIdentityDelete builder.
func (fid *FederatedIdentityDelete) Where(ps ...predicate.FederatedIdentity) *FederatedIdentityDelete {
	fid.mutation.Where(ps...)
	return fid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fid *FederatedIdentityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fid.sqlExec, fid.mutation, fid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fid *FederatedIdentityDelete) ExecX(ctx context.Context) int {
	n, err := fid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fid *FederatedIdentityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(federatedidentity.Table, sqlgraph.NewFieldSpec(federatedidentity.FieldID, field.TypeInt))
	if ps := fid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fid.mutation.done = true
	return affected, err
}

// FederatedIdentityDeleteOne is the builder for deleting a single FederatedIdentity entity.
type FederatedIdentityDeleteOne struct {
	fid *FederatedIdentityDelete
}

// Where appends a list predicates to the FederatedIdentityDelete builder.
func (fido *FederatedIdentityDeleteOne) Where(ps ...predicate.FederatedIdentity) *FederatedIdentityDeleteOne {
	fido.fid.mutation.Where(ps...)
	return fido
}

// Exec executes the deletion query.
func (fido *FederatedIdentityDeleteOne) Exec(ctx context.Context) error {
	n, err := fido.fid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{federatedidentity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fido *FederatedIdentityDeleteOne) ExecX(ctx context.Context) {
	if err := fido.Exec(ctx); err != nil {
		panic(err)
	}
}
