// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/federatedidentity"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// FederatedIdentity is the model entity for the FederatedIdentity schema.
type FederatedIdentity struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// UnionID holds the value of the "union_id" field.
	UnionID string `json:"union_id,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FederatedIdentityQuery when eager-loading is set.
	Edges        FederatedIdentityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FederatedIdentityEdges holds the relations/edges for other nodes in the graph.
type FederatedIdentityEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FederatedIdentityEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FederatedIdentity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case federatedidentity.FieldID, federatedidentity.FieldUserID:
			values[i] = new(sql.NullInt64)
		case federatedidentity.FieldProvider, federatedidentity.FieldSubject, federatedidentity.FieldUnionID:
			values[i] = new(sql.NullString)
		case federatedidentity.FieldCreatedAt, federatedidentity.FieldUpdatedAt, federatedidentity.FieldDeletedAt, federatedidentity.FieldLastUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FederatedIdentity fields.
func (fi *FederatedIdentity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case federatedidentity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			fi.ID = int(value.Int64)
		case federatedidentity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				fi.CreatedAt = value.Time
			}
		case federatedidentity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				fi.UpdatedAt = value.Time
			}
		case federatedidentity.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				fi.DeletedAt = new(time.Time)
				*fi.DeletedAt = value.Time
			}
		case federatedidentity.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				fi.UserID = int(value.Int64)
			}
		case federatedidentity.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				fi.Provider = value.String
			}
		case federatedidentity.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				fi.Subject = value.String
			}
		case federatedidentity.FieldUnionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field union_id", values[i])
			} else if value.Valid {
				fi.UnionID = value.String
			}
		case federatedidentity.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				fi.LastUsedAt = new(time.Time)
				*fi.LastUsedAt = value.Time
			}
		default:
			fi.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FederatedIdentity.
// This includes values selected through modifiers, order, etc.
func (fi *FederatedIdentity) Value(name string) (ent.Value, error) {
	return fi.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the FederatedIdentity entity.
func (fi *FederatedIdentity) QueryUser() *UserQuery {
	return NewFederatedIdentityClient(fi.config).QueryUser(fi)
}

// Update returns a builder for updating this FederatedIdentity.
// Note that you need to call FederatedIdentity.Unwrap() before calling this method if this FederatedIdentity
// was returned from a transaction, and the transaction was committed or rolled back.
func (fi *FederatedIdentity) Update() *FederatedIdentityUpdateOne {
	return NewFederatedIdentityClient(fi.config).UpdateOne(fi)
}

// Unwrap unwraps the FederatedIdentity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (fi *FederatedIdentity) Unwrap() *FederatedIdentity {
	_tx, ok := fi.config.driver.(*txDriver)
	if !ok {
		panic("ent: FederatedIdentity is not a transactional entity")
	}
	fi.config.driver = _tx.drv
	return fi
}

// String implements the fmt.Stringer.
func (fi *FederatedIdentity) String() string {
	var builder strings.Builder
	builder.WriteString("FederatedIdentity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", fi.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fi.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fi.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := fi.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", fi.UserID))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(fi.Provider)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(fi.Subject)
	builder.WriteString(", ")
	builder.WriteString("union_id=")
	builder.WriteString(fi.UnionID)
	builder.WriteString(", ")
	if v := fi.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SetUser manually set the edge as loaded state.
func (e *FederatedIdentity) SetUser(v *User) {
	e.Edges.User = v
	e.Edges.loadedTypes[0] = true
}

// FederatedIdentities is a parsable slice of FederatedIdentity.
type FederatedIdentities []*FederatedIdentity
